---

# Purpose: Create a point-in-time copy of all current data stored in Prometheus.

- name: Backup Prometheus data
  hosts: prometheus
  become: true
  roles:
    - global

  tasks:
    - name: Import database_backup.yml from prometheus_setup role
      ansible.builtin.import_role:
        name: prometheus_setup
        tasks_from: database_backup.yml
