---
tinyproxy_client_enabled: true
tinyproxy_client_proxy_scheme: http
tinyproxy_client_proxy_host: "{{ groups['fproxy'] | first }}"
tinyproxy_client_proxy_port: "{{ hostvars[groups['fproxy'] | first].tinyproxy_setup_port | default(8888) }}"

tinyproxy_client_manage_shell_proxy: true
tinyproxy_client_manage_apt_proxy: true

tinyproxy_client_no_proxy:
  - localhost
  - 127.0.0.1
  - ::1

tinyproxy_client_shell_proxy_path: /etc/profile.d/fproxy-proxy.sh
tinyproxy_client_apt_proxy_path: /etc/apt/apt.conf.d/80fproxy-proxy

tinyproxy_client_proxy_url: >-
  {{
    tinyproxy_client_proxy_scheme ~ '://' ~
    tinyproxy_client_proxy_host ~ ':' ~
    (tinyproxy_client_proxy_port | string)
  }}
tinyproxy_client_no_proxy_value: "{{ tinyproxy_client_no_proxy | join(',') }}"
