---
# Purpose: Deploy updates on Linux hosts

- name: Update linux
  hosts: linux
  become: true
  tasks:
    - name: Update Linux hosts
      ansible.builtin.import_role:
        name: linux
        tasks_from: updates
