---

vms_os: ubuntu_24_server
vms_autoinstall: true
vms_enable_serial_terminal: false
vms_additional_packages: []
python3_version: 3.12
python3_venv_folder: "/opt/python_{{ python3_version }}"
postgresql_setup_version: 14

nginx_setup_disable_default_site: true

node_exporter_port: 9200
