---

- name: Ensure backup directory exists
  ansible.builtin.file:
    path: "{{ plex_setup_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Stop Plex service before backup
  ansible.builtin.service:
    name: plexmediaserver
    state: stopped

- name: Archive Plex data directory
  community.general.archive:
    path: "{{ plex_setup_data_dir }}"
    dest: "{{ plex_setup_backup_file }}"
    mode: "0755"
    format: gz
    remove: false

- name: Start Plex service after backup
  ansible.builtin.service:
    name: plexmediaserver
    state: started

- name: Find Plex backups
  ansible.builtin.find:
    paths: "{{ plex_setup_backup_dir }}"
    patterns: "plex_backup_*.tar.gz"
    recurse: false
  register: plex_setup_backups

- name: Remove old backups and keep the latest 7
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ (plex_setup_backups.files |
    sort(attribute='mtime'))[:(plex_setup_backups.matched - 7)] }}"
  when: plex_setup_backups.matched > 7
