---
lidarr_setup_version: 2.13.3.4711
lidarr_setup_config_dir: "/config"
lidarr_setup_port: 8686
lidarr_setup_ssl_port: 6868
lidarr_setup_debug_level: debug

lidarr_setup_pg_port: 5432
lidarr_setup_pg_host: "{{ global_ip_addresses[groups['pgdb'][0]] }}"

# See vault for the following variables
# lidarr_setup_db_name
# lidarr_setup_db_log
# lidarr_setup_db_user
# lidarr_setup_db_password

lidarr_setup_mount_point: /nfs/backups
lidarr_setup_backup_prefix: "lidarr_"
lidarr_setup_backup_filename: "{{ lidarr_setup_backup_prefix }}{{ ansible_date_time.date }}.sqlc"
lidarr_setup_backups_dir: "{{ lidarr_setup_mount_point }}/lidarr"
lidarr_setup_backup_path: "{{ lidarr_setup_backups_dir }}/{{ lidarr_setup_backup_filename }}"
lidarr_setup_restore_path: ""

lidarr_setup_api_url: "http://127.0.0.1:{{ lidarr_setup_port }}"
lidarr_setup_api_validate_certs: false

lidarr_setup_root_folders:
  - name: Music
    path: /music
    default_quality_profile_name: "Lossless"
    default_metadata_profile_name: "Standard"
    default_monitor_option: "all"
    default_new_item_monitor_option: "all"
    default_tags: []

lidarr_setup_download_clients:
  - name: sabnzbd
    implementation: Sabnzbd
    enable: true
    priority: 1
    fields:
      host: "{{ groups['sabnzbd'][0] }}"
      port: 8080
      category: music

lidarr_setup_indexers:
  - name: nzbgeek
    implementation: Newznab
    enable_rss: true
    enable_automatic_search: true
    enable_interactive_search: true
    priority: 1
    download_client_name: sabnzbd
    fields:
      baseUrl: https://api.nzbgeek.info
      apiKey: "{{ nzbgeek_api_key }}"
      categories:
        - 2000
        - 2010
        - 2020
        - 2030
        - 2040
        - 2050
        - 2060
  - name: nzb.su
    implementation: Newznab
    enable_rss: true
    enable_automatic_search: true
    enable_interactive_search: true
    priority: 1
    download_client_name: sabnzbd
    fields:
      baseUrl: https://api.nzb.su
      apiKey: "{{ nzbsu_api_key }}"
      categories:
        - 2000
        - 2010
        - 2020
        - 2030
        - 2040
        - 2050
        - 2060

lidarr_setup_root_folder_default_quality_profile_name: "Any"
lidarr_setup_root_folder_default_metadata_profile_name: "Standard"
lidarr_setup_root_folder_default_monitor_option: "all"
lidarr_setup_root_folder_default_new_item_monitor_option: "all"

lidarr_setup_configure_api: >-
  {{
    (lidarr_setup_root_folders | length > 0)
    or (lidarr_setup_download_clients | length > 0)
    or (lidarr_setup_indexers | length > 0)
  }}

lidarr_setup_authentication_method: "External" # Options: Basic, Forms, External
lidarr_setup_authentication_required: "DisabledForLocalAddresses" # Options: Enabled, DisabledForLocalAddresses
