---
- name: Restart nginxlog exporter
  ansible.builtin.systemd:
    name: nginxlog-exporter
    state: restarted
    daemon_reload: true

- name: Reload nginx for traffic logging
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
