---
- name: Create user primary groups
  ansible.builtin.group:
    name: "{{ user.group | default(user.username) }}"
    gid: "{{ user.gid | default(omit) }}"
    system: "{{ user.system | default(false) }}"
    state: present
  when: user.group is defined or user.gid is defined or (user.system | default(false) | bool)
  loop: "{{ users_list | default([]) }}"
  loop_control:
    label: "{{ user.group | default(user.username) }}"
    loop_var: user

- name: Add a new user
  ansible.builtin.user:
    name: "{{ user.username }}"
    password: "{{ (user.password | password_hash('sha512')) if user.password is defined else omit }}"
    update_password: always
    shell: "{{ user.shell | default('/usr/sbin/nologin' if (user.system | default(false) | bool) else '/bin/bash') }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.group | default(user.username if (user.system | default(false) | bool) else omit) }}"
    system: "{{ user.system | default(false) }}"
    state: present
    create_home: "{{ user.create_home | default(user.home is defined) }}"
  loop: "{{ users_list | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user

- name: Join groups
  ansible.builtin.user:
    name: "{{ user.username }}"
    groups: "{{ user.groups | join(',') }}"
  when: user.groups is defined
  loop: "{{ users_list | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user

- name: Set a user-defined home folder
  ansible.builtin.user:
    name: "{{ user.username }}"
    home: "{{ user.home }}"
    move_home: true
  when: user.home is defined
  loop: "{{ users_list | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user

- name: Add user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ user.username }}"
    line: "{{ user.username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  when: user.visudo | default(false) | bool
  loop: "{{ users_list | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
