[vms]
ecube-0 vms_proxmox_node=pve-2 vms_clone=false
ecube-1 vms_proxmox_node=pve-1 vms_clone=false

[baremetal]
ecube-2 pihole_cname_entries='[{"domain": "demo.ecube.com", "target": "rproxy-0.refol.us"}]'

[linux]
ecube-0
ecube-1
ecube-2

[ecube]
ecube-0
ecube-1
ecube-2

[pgdb]
ecube-0
ecube-1
ecube-2

[rproxy_main]
rproxy-0

[rproxy_primary]
rproxy-1

[rproxy_secondary]
rproxy-2

[rproxy:children]
rproxy_main
rproxy_primary
rproxy_secondary

[removable]
ecube-0
ecube-1

[python]
ecube-0
ecube-1
ecube-2

[certs]
rproxy-0
