---
nginx_prometheus_exporter_setup_version: "1.5.1"
nginx_prometheus_exporter_setup_download_base_url: "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v"
nginx_prometheus_exporter_setup_platform: "linux_amd64"
nginx_prometheus_exporter_setup_installdir: /opt/nginx-prometheus-exporter_{{ nginx_prometheus_exporter_setup_version }}_{{ nginx_prometheus_exporter_setup_platform }}
nginx_prometheus_exporter_setup_home: "/opt/nginx-prometheus-exporter"
nginx_prometheus_exporter_setup_binary: "/usr/local/bin/nginx-prometheus-exporter"
nginx_prometheus_exporter_setup_mode: "0755"
nginx_prometheus_exporter_setup_service_name: "nginx-prometheus-exporter"
nginx_prometheus_exporter_setup_service_file: "/etc/systemd/system/nginx-prometheus-exporter.service"
nginx_prometheus_exporter_setup_service_mode: "0644"
nginx_prometheus_exporter_setup_user: "nginx-prometheus-exporter"
nginx_prometheus_exporter_setup_group: "nginx-prometheus-exporter"
nginx_prometheus_exporter_setup_listen_address: "0.0.0.0:9113"
nginx_prometheus_exporter_setup_telemetry_path: "/metrics"
nginx_prometheus_exporter_setup_scrape_uri: "http://127.0.0.1:9114/stub_status"
nginx_prometheus_exporter_setup_nginx_status_site_name: "nginx-prometheus-exporter-status"
nginx_prometheus_exporter_setup_nginx_status_listen_address: "127.0.0.1:9114"
nginx_prometheus_exporter_setup_nginx_status_path: "/stub_status"
