---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart blackbox_exporter service
  ansible.builtin.systemd:
    name: "{{ blackbox_exporter_setup_service_name }}"
    state: restarted
    enabled: true